import type { InsertQuestion, InsertStudyMaterial, InsertFlashcard } from "@shared/schema";

/**
 * Official questions based on "Australian Citizenship: Our Common Bond" (2020)
 * Source: https://immi.homeaffairs.gov.au/citizenship-subsite/files/our-common-bond-testable.pdf
 * 
 * Categories mapping (matching official PDF structure):
 * 1 - Part 1: Australia and its people
 * 2 - Part 2: Australia's democratic beliefs, rights and liberties
 * 3 - Part 3: Government and the law in Australia
 * 4 - Part 4: Australian values
 */

// PART 1: AUSTRALIA AND ITS PEOPLE
export const officialQuestions: Omit<InsertQuestion, 'createdAt'>[] = [
  // Indigenous Australia Questions (Part 1)
  {
    categoryId: 1,
    question: "Who are Australia's first inhabitants?",
    optionA: "British settlers",
    optionB: "Aboriginal and Torres Strait Islander peoples",
    optionC: "Dutch explorers",
    optionD: "Asian migrants",
    correctAnswer: "B",
    explanation: "Aboriginal and Torres Strait Islander peoples are Australia's first inhabitants, with the oldest continuous cultures and traditions in the world.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 1 - Aboriginal and Torres Strait Islander peoples",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 1,
    question: "How long have Aboriginal and Torres Strait Islander peoples lived in Australia?",
    optionA: "Between 10,000 and 20,000 years",
    optionB: "Between 25,000 and 30,000 years",
    optionC: "Between 65,000 and 40,000 years",
    optionD: "Between 100,000 and 80,000 years",
    correctAnswer: "C",
    explanation: "Archaeological records indicate that Aboriginal peoples arrived in Australia between 65,000 and 40,000 years ago.",
    difficulty: "medium",
    source: "official_guide",
    sourceReference: "Part 1 - Aboriginal and Torres Strait Islander peoples",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 1,
    question: "Where are Torres Strait Islander people from?",
    optionA: "Mainland Australia",
    optionB: "Tasmania",
    optionC: "Islands between Queensland and Papua New Guinea",
    optionD: "New Zealand",
    correctAnswer: "C",
    explanation: "Torres Strait Islander people are from islands between the northern tip of Queensland and Papua New Guinea.",
    difficulty: "medium",
    source: "official_guide",
    sourceReference: "Part 1 - Aboriginal and Torres Strait Islander peoples",
    isValuesQuestion: false,
    isActive: true
  },

  // History Questions (Category 2)
  {
    categoryId: 1,
    question: "When did European settlement begin in Australia?",
    optionA: "1788",
    optionB: "1801",
    optionC: "1770",
    optionD: "1851",
    correctAnswer: "A",
    explanation: "European settlement started when the First Fleet arrived from Great Britain on 26 January 1788.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 1 - Early days of European settlement",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 1,
    question: "What was the First Fleet?",
    optionA: "A naval battle fleet",
    optionB: "The first 11 convict ships from Great Britain",
    optionC: "Trading ships from Asia",
    optionD: "Exploration vessels",
    correctAnswer: "B",
    explanation: "The First Fleet refers to the first 11 convict ships that arrived from Great Britain in 1788.",
    difficulty: "medium",
    source: "official_guide",
    sourceReference: "Part 1 - Early days of European settlement",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 1,
    question: "Who was the first Governor of the colony of New South Wales?",
    optionA: "Captain James Cook",
    optionB: "Captain Arthur Phillip",
    optionC: "Governor Lachlan Macquarie",
    optionD: "Sir Edmund Barton",
    correctAnswer: "B",
    explanation: "Captain Arthur Phillip was the first Governor of the colony of New South Wales.",
    difficulty: "medium",
    source: "official_guide",
    sourceReference: "Part 1 - Early days of European settlement",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 1,
    question: "When did the Australian gold rush begin?",
    optionA: "1788",
    optionB: "1901",
    optionC: "1851",
    optionD: "1967",
    correctAnswer: "C",
    explanation: "The gold rush began in 1851 when gold was discovered in New South Wales and Victoria.",
    difficulty: "medium",
    source: "official_guide",
    sourceReference: "Part 1 - Early days of European settlement",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 1,
    question: "When did the separate colonies unite to form the Commonwealth of Australia?",
    optionA: "1788",
    optionB: "1851",
    optionC: "1901",
    optionD: "1967",
    correctAnswer: "C",
    explanation: "In 1901, the separate colonies were united into a federation of states called the Commonwealth of Australia.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 1 - The nation of Australia",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 1,
    question: "When were Aboriginal and Torres Strait Islander peoples included in official population estimates?",
    optionA: "1788",
    optionB: "1901",
    optionC: "After the 1967 Referendum",
    optionD: "1851",
    correctAnswer: "C",
    explanation: "Aboriginal and Torres Strait Islander peoples were not included in official population estimates until after the Referendum in 1967.",
    difficulty: "medium",
    source: "official_guide",
    sourceReference: "Part 1 - The nation of Australia",
    isValuesQuestion: false,
    isActive: true
  },

  // PART 2: AUSTRALIA'S DEMOCRATIC BELIEFS, RIGHTS AND LIBERTIES
  // Australian Values Questions (Category 1)
  {
    categoryId: 2,
    question: "What type of government does Australia have?",
    optionA: "Monarchy",
    optionB: "Democracy",
    optionC: "Dictatorship",
    optionD: "Republic",
    correctAnswer: "B",
    explanation: "Australia is a democracy where the government is elected by the people.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 2 - Australia's democratic beliefs",
    isValuesQuestion: true,
    isActive: true
  },
  {
    categoryId: 1,
    question: "What is the common bond that unites all Australians?",
    optionA: "Religion",
    optionB: "Language",
    optionC: "Citizenship",
    optionD: "Ethnicity",
    correctAnswer: "C",
    explanation: "Citizenship is the common bond uniting all Australians, regardless of their background.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 1 - A message to you",
    isValuesQuestion: true,
    isActive: true
  },
  {
    categoryId: 1,
    question: "What does the Australian Citizenship Pledge require you to pledge loyalty to?",
    optionA: "The British Crown",
    optionB: "Australia and its people",
    optionC: "The Prime Minister",
    optionD: "The United Nations",
    correctAnswer: "B",
    explanation: "The Citizenship Pledge requires pledging loyalty to Australia and its people.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 1 - The Australian Citizenship Pledge",
    isValuesQuestion: true,
    isActive: true
  },
  {
    categoryId: 2,
    question: "What freedoms are guaranteed in Australia?",
    optionA: "Freedom of speech and freedom of religion",
    optionB: "Freedom to disobey laws",
    optionC: "Freedom from taxation",
    optionD: "Freedom from government",
    correctAnswer: "A",
    explanation: "Australia guarantees freedom of speech and freedom of religion, among other freedoms.",
    difficulty: "medium",
    source: "official_guide",
    sourceReference: "Part 2 - Australia's democratic beliefs",
    isValuesQuestion: true,
    isActive: true
  },
  {
    categoryId: 4,
    question: "In Australia, can you encourage violence against a person or group?",
    optionA: "Yes, if you disagree with them",
    optionB: "Yes, as part of free speech",
    optionC: "No, it is against Australian values and the law",
    optionD: "Yes, in certain circumstances",
    correctAnswer: "C",
    explanation: "Encouraging violence against a person or group is against Australian values and the law.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 4 - Australian values",
    isValuesQuestion: true,
    isActive: true
  },
  {
    categoryId: 4,
    question: "Should people in Australia make an effort to learn English?",
    optionA: "No, it is not important",
    optionB: "Yes, it helps you to participate in Australian society",
    optionC: "Only if you work in government",
    optionD: "No, you can use interpreters for everything",
    correctAnswer: "B",
    explanation: "Learning English helps you to participate fully in Australian society and is encouraged.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 4 - Australian values",
    isValuesQuestion: true,
    isActive: true
  },
  {
    categoryId: 4,
    question: "Are men and women equal in Australia?",
    optionA: "No, men have more rights",
    optionB: "No, women have more rights",
    optionC: "Yes, they have equal rights and opportunities",
    optionD: "Only in certain situations",
    correctAnswer: "C",
    explanation: "Australian values include equality between men and women. Both have equal rights and opportunities.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 4 - Australian values",
    isValuesQuestion: true,
    isActive: true
  },
  {
    categoryId: 4,
    question: "What does 'mateship' mean in Australian values?",
    optionA: "Only helping your friends",
    optionB: "Friendship, support and looking out for each other",
    optionC: "Competing against others",
    optionD: "Avoiding strangers",
    correctAnswer: "B",
    explanation: "Mateship is an important Australian value meaning friendship, support and looking out for each other.",
    difficulty: "medium",
    source: "official_guide",
    sourceReference: "Part 4 - Australian values",
    isValuesQuestion: true,
    isActive: true
  },

  // PART 3: GOVERNMENT AND THE LAW IN AUSTRALIA
  // Government Questions (Category 4)
  {
    categoryId: 3,
    question: "What is the name of Australia's system of government?",
    optionA: "Parliamentary democracy",
    optionB: "Presidential democracy",
    optionC: "Communist system",
    optionD: "Absolute monarchy",
    correctAnswer: "A",
    explanation: "Australia has a parliamentary democracy, where the Parliament makes laws and the government is formed by the party with majority support.",
    difficulty: "medium",
    source: "official_guide",
    sourceReference: "Part 3 - Government and the law",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 3,
    question: "Who is the head of state of Australia?",
    optionA: "The Prime Minister",
    optionB: "The Governor-General",
    optionC: "The British Monarch",
    optionD: "The President",
    correctAnswer: "C",
    explanation: "The British Monarch (currently King Charles III) is Australia's head of state, represented in Australia by the Governor-General.",
    difficulty: "medium",
    source: "official_guide",
    sourceReference: "Part 3 - Government and the law",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 3,
    question: "Who represents the King/Queen in Australia?",
    optionA: "The Prime Minister",
    optionB: "The Governor-General",
    optionC: "The Chief Justice",
    optionD: "The Speaker of the House",
    correctAnswer: "B",
    explanation: "The Governor-General represents the King/Queen in Australia and is appointed by the Monarch on the advice of the Prime Minister.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 3 - Government and the law",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 3,
    question: "How many levels of government are there in Australia?",
    optionA: "One",
    optionB: "Two",
    optionC: "Three",
    optionD: "Four",
    correctAnswer: "C",
    explanation: "Australia has three levels of government: federal (Commonwealth), state/territory, and local.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 3 - Government and the law",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 1,
    question: "What are the colors of the Australian flag?",
    optionA: "Red, white and blue",
    optionB: "Green and gold",
    optionC: "Blue, red and white",
    optionD: "Blue, white and red",
    correctAnswer: "A",
    explanation: "The Australian flag has three colors: red, white, and blue.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 1 - Australian symbols",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 3,
    question: "How many houses does the Australian Parliament have?",
    optionA: "One",
    optionB: "Two",
    optionC: "Three",
    optionD: "Four",
    correctAnswer: "B",
    explanation: "The Australian Parliament has two houses: the House of Representatives and the Senate.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 3 - Government and the law",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 3,
    question: "Who has the power to make and change laws in Australia?",
    optionA: "The Prime Minister",
    optionB: "The Governor-General",
    optionC: "The Parliament",
    optionD: "The High Court",
    correctAnswer: "C",
    explanation: "The Parliament has the power to make and change laws in Australia.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 3 - Government and the law",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 3,
    question: "What is the minimum age for voting in Australia?",
    optionA: "16 years",
    optionB: "18 years",
    optionC: "21 years",
    optionD: "25 years",
    correctAnswer: "B",
    explanation: "Australian citizens aged 18 years and over have the right and responsibility to vote.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 3 - Government and the law",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 3,
    question: "Is voting compulsory in Australian federal and state elections?",
    optionA: "No, it is optional",
    optionB: "Yes, it is compulsory for citizens 18 and over",
    optionC: "Only for federal elections",
    optionD: "Only for state elections",
    correctAnswer: "B",
    explanation: "Voting is compulsory for all Australian citizens aged 18 years and over in federal and state elections.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 3 - Government and the law",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 1,
    question: "What is the official name of Australia?",
    optionA: "Australia",
    optionB: "The Commonwealth of Australia",
    optionC: "The Australian Federation",
    optionD: "The Australian Commonwealth",
    correctAnswer: "B",
    explanation: "The official name of Australia is the Commonwealth of Australia.",
    difficulty: "medium",
    source: "official_guide",
    sourceReference: "Part 1 - The nation of Australia",
    isValuesQuestion: false,
    isActive: true
  },

  // Geography Questions (Category 3)
  {
    categoryId: 1,
    question: "What is the capital city of Australia?",
    optionA: "Sydney",
    optionB: "Melbourne",
    optionC: "Canberra",
    optionD: "Brisbane",
    correctAnswer: "C",
    explanation: "Canberra is the capital city of Australia.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 1 - Australia and its people",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 1,
    question: "How many states and territories does Australia have?",
    optionA: "Six states and two territories",
    optionB: "Seven states and one territory",
    optionC: "Five states and three territories",
    optionD: "Eight states",
    correctAnswer: "A",
    explanation: "Australia has six states and two mainland territories.",
    difficulty: "medium",
    source: "official_guide",
    sourceReference: "Part 1 - Australia and its people",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 1,
    question: "What are Australia's national colors?",
    optionA: "Red and white",
    optionB: "Blue and white",
    optionC: "Green and gold",
    optionD: "Red and blue",
    correctAnswer: "C",
    explanation: "Green and gold are Australia's national colors.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 1 - Australian symbols",
    isValuesQuestion: false,
    isActive: true
  },

  // Culture & Society Questions (Category 6)
  {
    categoryId: 1,
    question: "What is Australia's national flower?",
    optionA: "Rose",
    optionB: "Golden wattle",
    optionC: "Waratah",
    optionD: "Eucalyptus",
    correctAnswer: "B",
    explanation: "The golden wattle is Australia's national flower.",
    difficulty: "medium",
    source: "official_guide",
    sourceReference: "Part 1 - Australian symbols",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 1,
    question: "What is the name of Australia's national anthem?",
    optionA: "God Save the King",
    optionB: "Waltzing Matilda",
    optionC: "Advance Australia Fair",
    optionD: "I Am Australian",
    correctAnswer: "C",
    explanation: "Australia's national anthem is 'Advance Australia Fair'.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 1 - Australian symbols",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 1,
    question: "What do we remember on Anzac Day?",
    optionA: "The day Australia became a nation",
    optionB: "The landing of the First Fleet",
    optionC: "The sacrifice of Australians who served and died in wars",
    optionD: "The gold rush",
    correctAnswer: "C",
    explanation: "Anzac Day (25 April) commemorates the sacrifice of Australians who served and died in wars, conflicts and peacekeeping operations.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 1 - Australian symbols",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 1,
    question: "When is Australia Day?",
    optionA: "1 January",
    optionB: "26 January",
    optionC: "25 April",
    optionD: "1 July",
    correctAnswer: "B",
    explanation: "Australia Day is celebrated on 26 January each year, marking the arrival of the First Fleet in 1788.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 1 - Australian symbols",
    isValuesQuestion: false,
    isActive: true
  },

  // PART 4: AUSTRALIAN VALUES - More values questions
  {
    categoryId: 2,
    question: "What does freedom of religion mean in Australia?",
    optionA: "Everyone must follow the same religion",
    optionB: "People can practice any religion or no religion",
    optionC: "Only Christian religions are allowed",
    optionD: "Religion is banned",
    correctAnswer: "B",
    explanation: "Freedom of religion means people can practice any religion they choose, or no religion at all.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 2 - Australia's democratic beliefs",
    isValuesQuestion: true,
    isActive: true
  },
  {
    categoryId: 4,
    question: "Do Australian values include respect for the freedom and dignity of the individual?",
    optionA: "No",
    optionB: "Only for certain groups",
    optionC: "Yes",
    optionD: "Only for citizens",
    correctAnswer: "C",
    explanation: "Respect for the freedom and dignity of each individual is a core Australian value.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 4 - Australian values",
    isValuesQuestion: true,
    isActive: true
  },
  {
    categoryId: 2,
    question: "What does the Rule of Law mean?",
    optionA: "Rich people are above the law",
    optionB: "Everyone must follow the law, including those who make it",
    optionC: "Politicians don't have to follow laws",
    optionD: "Only some people have to follow laws",
    correctAnswer: "B",
    explanation: "The Rule of Law means that everyone, including those who make the laws, must follow them.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 2 - Australia's democratic beliefs",
    isValuesQuestion: true,
    isActive: true
  },
  {
    categoryId: 4,
    question: "Is it acceptable in Australia to use violence to settle disagreements?",
    optionA: "Yes, if you are very angry",
    optionB: "Yes, in certain situations",
    optionC: "No, peaceful methods must be used",
    optionD: "Only in self-defense",
    correctAnswer: "C",
    explanation: "Violence is not acceptable for settling disagreements. Australians value peaceful conflict resolution.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 4 - Australian values",
    isValuesQuestion: true,
    isActive: true
  },
  {
    categoryId: 4,
    question: "What does equality of opportunity mean in Australia?",
    optionA: "Everyone gets exactly the same outcome",
    optionB: "People have the chance to achieve based on merit and hard work",
    optionC: "Some groups get special treatment",
    optionD: "Success is determined by family background",
    correctAnswer: "B",
    explanation: "Equality of opportunity means people have the chance to achieve and succeed based on merit and hard work, regardless of background.",
    difficulty: "medium",
    source: "official_guide",
    sourceReference: "Part 4 - Australian values",
    isValuesQuestion: true,
    isActive: true
  },

  // Additional Government Questions
  {
    categoryId: 3,
    question: "What is the role of the courts in Australia?",
    optionA: "To make laws",
    optionB: "To interpret and apply the law",
    optionC: "To elect the government",
    optionD: "To write the Constitution",
    correctAnswer: "B",
    explanation: "The role of courts is to interpret and apply the law, and to ensure laws are administered fairly.",
    difficulty: "medium",
    source: "official_guide",
    sourceReference: "Part 3 - Government and the law",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 3,
    question: "What is the highest court in Australia?",
    optionA: "The Supreme Court",
    optionB: "The Federal Court",
    optionC: "The High Court",
    optionD: "The District Court",
    correctAnswer: "C",
    explanation: "The High Court of Australia is the highest court and final court of appeal.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 3 - Government and the law",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 3,
    question: "Which political party or parties form the Australian Government?",
    optionA: "The party or coalition with the majority in the Senate",
    optionB: "The party or coalition with the majority in the House of Representatives",
    optionC: "The party chosen by the Governor-General",
    optionD: "All parties equally",
    correctAnswer: "B",
    explanation: "The party or coalition of parties with the majority of seats in the House of Representatives forms the government.",
    difficulty: "medium",
    source: "official_guide",
    sourceReference: "Part 3 - Government and the law",
    isValuesQuestion: false,
    isActive: true
  },

  // Additional Culture & Society
  {
    categoryId: 1,
    question: "From how many countries have people migrated to Australia?",
    optionA: "Around 50 countries",
    optionB: "Around 100 countries",
    optionC: "More than 200 countries",
    optionD: "Around 150 countries",
    correctAnswer: "C",
    explanation: "People from more than 200 countries have made Australia their home, making it one of the most diverse societies in the world.",
    difficulty: "medium",
    source: "official_guide",
    sourceReference: "Part 1 - A message to you",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 1,
    question: "Who were the first large group of migrants to Australia not from Europe?",
    optionA: "Indian people",
    optionB: "Chinese people",
    optionC: "Japanese people",
    optionD: "Vietnamese people",
    correctAnswer: "B",
    explanation: "Chinese people arriving during the gold rush were the first large group of migrants not from Europe.",
    difficulty: "medium",
    source: "official_guide",
    sourceReference: "Part 1 - Early days of European settlement",
    isValuesQuestion: false,
    isActive: true
  },

  // Additional questions from the official PDF
  {
    categoryId: 1,
    question: "When is Australia Day celebrated?",
    optionA: "1 January",
    optionB: "26 January",
    optionC: "25 April",
    optionD: "25 December",
    correctAnswer: "B",
    explanation: "Australia Day is celebrated on 26 January each year, the anniversary of the arrival of the First Fleet in 1788.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 1 - Important days for Australians",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 1,
    question: "When is Anzac Day commemorated?",
    optionA: "25 April",
    optionB: "26 January",
    optionC: "11 November",
    optionD: "1 July",
    correctAnswer: "A",
    explanation: "Anzac Day is commemorated on 25 April each year, remembering those who served and died in wars and peacekeeping operations.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 1 - Important days for Australians",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 1,
    question: "What is Australia's national flower?",
    optionA: "Rose",
    optionB: "Waratah",
    optionC: "Golden wattle",
    optionD: "Eucalyptus",
    correctAnswer: "C",
    explanation: "The golden wattle is Australia's national flower. It has bright green leaves and golden yellow flowers in spring.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 1 - Australia's symbols",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 1,
    question: "What are Australia's national colours?",
    optionA: "Red and white",
    optionB: "Blue and white",
    optionC: "Green and gold",
    optionD: "Red and blue",
    correctAnswer: "C",
    explanation: "Australia's national colours are green and gold, the colours of the golden wattle.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 1 - Australia's symbols",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 1,
    question: "What is the capital city of Western Australia?",
    optionA: "Adelaide",
    optionB: "Perth",
    optionC: "Darwin",
    optionD: "Brisbane",
    correctAnswer: "B",
    explanation: "Perth is the capital city of Western Australia, the largest state.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 1 - Australia's states and territories",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 1,
    question: "Which is the smallest mainland state in Australia?",
    optionA: "Tasmania",
    optionB: "Victoria",
    optionC: "South Australia",
    optionD: "Australian Capital Territory",
    correctAnswer: "B",
    explanation: "Victoria is the smallest of the mainland states. Its capital city is Melbourne.",
    difficulty: "medium",
    source: "official_guide",
    sourceReference: "Part 1 - Australia's states and territories",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 1,
    question: "What colours are on the Australian Aboriginal Flag?",
    optionA: "Red, yellow and green",
    optionB: "Black, red and yellow",
    optionC: "Blue, white and red",
    optionD: "Green, blue and white",
    correctAnswer: "B",
    explanation: "The Australian Aboriginal Flag is black (representing Aboriginal peoples), red (representing the earth) and yellow (representing the sun).",
    difficulty: "medium",
    source: "official_guide",
    sourceReference: "Part 1 - Australia's flags",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 1,
    question: "How many points does the Commonwealth Star have on the Australian National Flag?",
    optionA: "Five points",
    optionB: "Six points",
    optionC: "Seven points",
    optionD: "Eight points",
    correctAnswer: "C",
    explanation: "The Commonwealth Star has seven points - one for each of the six states and one for the territories.",
    difficulty: "medium",
    source: "official_guide",
    sourceReference: "Part 1 - Australia's flags",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 2,
    question: "What does 'a fair go' mean in Australian society?",
    optionA: "Everyone should receive government assistance",
    optionB: "What someone achieves should result from their talents, work and effort",
    optionC: "Everyone should earn the same income",
    optionD: "Only wealthy people should succeed",
    correctAnswer: "B",
    explanation: "A 'fair go' means equal opportunity - what someone achieves should result from their talents, work and effort, rather than their wealth or background.",
    difficulty: "medium",
    source: "official_guide",
    sourceReference: "Part 2 - Our equalities",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 2,
    question: "Is Australia's government secular?",
    optionA: "No, it follows Christian law",
    optionB: "Yes, it operates separately from religious entities",
    optionC: "No, it follows Islamic law",
    optionD: "Yes, but only for certain states",
    correctAnswer: "B",
    explanation: "The government in Australia is secular, which means it operates separately from churches or other religious entities.",
    difficulty: "medium",
    source: "official_guide",
    sourceReference: "Part 2 - Our freedoms",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 3,
    question: "How many senators does each state elect to the Senate?",
    optionA: "10 senators",
    optionB: "12 senators",
    optionC: "8 senators",
    optionD: "6 senators",
    correctAnswer: "B",
    explanation: "Each state elects 12 senators to represent them in the Senate, regardless of the state's size or population.",
    difficulty: "medium",
    source: "official_guide",
    sourceReference: "Part 3 - Government and the law",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 3,
    question: "How many senators are there in total in the Australian Senate?",
    optionA: "72 senators",
    optionB: "76 senators",
    optionC: "80 senators",
    optionD: "100 senators",
    correctAnswer: "B",
    explanation: "There are 76 senators in total: 12 from each of the 6 states (72) plus 2 each from the ACT and NT (4).",
    difficulty: "medium",
    source: "official_guide",
    sourceReference: "Part 3 - Government and the law",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 3,
    question: "Approximately how many members are in the House of Representatives?",
    optionA: "Over 100 members",
    optionB: "Over 150 members",
    optionC: "Over 200 members",
    optionD: "76 members",
    correctAnswer: "B",
    explanation: "There are over 150 members elected to the House of Representatives, with numbers based on each state's population.",
    difficulty: "medium",
    source: "official_guide",
    sourceReference: "Part 3 - Government and the law",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 3,
    question: "What is another name for the Senate?",
    optionA: "The Lower House",
    optionB: "The People's House",
    optionC: "The Upper House",
    optionD: "The Commonwealth House",
    correctAnswer: "C",
    explanation: "The Senate is also called the Upper House, the House of Review, or the States' House.",
    difficulty: "medium",
    source: "official_guide",
    sourceReference: "Part 3 - Government and the law",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 3,
    question: "Who is Australia's Head of State?",
    optionA: "The Prime Minister",
    optionB: "The Governor-General",
    optionC: "The King of Australia",
    optionD: "The President",
    correctAnswer: "C",
    explanation: "Australia's Head of State is the King of Australia, His Majesty King Charles III.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 3 - Government and the law",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 3,
    question: "What is the role of the Governor-General?",
    optionA: "To lead the government",
    optionB: "To represent the King in Australia",
    optionC: "To make laws",
    optionD: "To judge court cases",
    correctAnswer: "B",
    explanation: "The Governor-General is the representative of the Head of State (the King) in Australia.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 3 - Government and the law",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 3,
    question: "Is voting by secret ballot in Australia?",
    optionA: "No, everyone knows who you vote for",
    optionB: "Yes, no one is allowed to know whom you voted for unless you tell them",
    optionC: "Only in federal elections",
    optionD: "Only for people over 30",
    correctAnswer: "B",
    explanation: "In Australia, voting is by secret ballot, so you are free and safe to vote for any candidate without others knowing.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 3 - Government and the law",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 4,
    question: "What are Australian values based on?",
    optionA: "Wealth and prosperity only",
    optionB: "Freedom, respect, fairness and equality of opportunity",
    optionC: "Military strength",
    optionD: "Religious teachings",
    correctAnswer: "B",
    explanation: "Australian values are based on freedom, respect, fairness and equality of opportunity.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 4 - Australian values",
    isValuesQuestion: true,
    isActive: true
  },
  {
    categoryId: 4,
    question: "Do Australian laws apply to all people in Australia?",
    optionA: "No, only to citizens",
    optionB: "Yes, regardless of background or culture",
    optionC: "Only to permanent residents",
    optionD: "Only to people born in Australia",
    correctAnswer: "B",
    explanation: "Australian laws apply to all people in Australia, regardless of background or culture.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 4 - Australian values",
    isValuesQuestion: true,
    isActive: true
  },

  // Additional Part 2 Questions - Democratic Beliefs, Rights and Liberties
  {
    categoryId: 2,
    question: "In Australia, are people free to choose their own religion?",
    optionA: "No, Australia has an official religion",
    optionB: "Yes, everyone is free to follow any religion or no religion",
    optionC: "Only Christian religions are allowed",
    optionD: "No, religion is banned",
    correctAnswer: "B",
    explanation: "Freedom of religion is a fundamental Australian value. People can practice any religion they choose, or no religion at all.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 2 - Our freedoms",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 2,
    question: "Can Australians peacefully protest against government decisions?",
    optionA: "No, protesting is illegal",
    optionB: "Yes, peaceful protest is a right",
    optionC: "Only if the government approves",
    optionD: "Only during elections",
    correctAnswer: "B",
    explanation: "The right to peaceful protest is an important democratic freedom in Australia.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 2 - Our freedoms",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 2,
    question: "Are Australians free to say and write what they think?",
    optionA: "No, speech is controlled by the government",
    optionB: "Yes, within the limits of Australian law",
    optionC: "Only if it supports the government",
    optionD: "No, all speech must be approved",
    correctAnswer: "B",
    explanation: "Freedom of speech is a fundamental right in Australia, exercised within the limits of the law.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 2 - Our freedoms",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 2,
    question: "What does equality before the law mean?",
    optionA: "Rich people have more rights",
    optionB: "All people are treated equally by the law",
    optionC: "Citizens have more rights than non-citizens",
    optionD: "Men and women have different legal rights",
    correctAnswer: "B",
    explanation: "Equality before the law means all people are treated equally by the law, regardless of their background.",
    difficulty: "medium",
    source: "official_guide",
    sourceReference: "Part 2 - Our equalities",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 2,
    question: "Who has the right to freedom of speech and freedom of expression in Australia?",
    optionA: "Only citizens",
    optionB: "Only permanent residents",
    optionC: "All people in Australia",
    optionD: "Only people born in Australia",
    correctAnswer: "C",
    explanation: "Freedom of speech and expression are rights enjoyed by all people in Australia.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 2 - Our freedoms",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 2,
    question: "Does respect for the law make Australian society safer for everyone?",
    optionA: "No, laws don't affect safety",
    optionB: "Yes, respect for the law helps keep Australia safe",
    optionC: "Only in cities",
    optionD: "Only for some people",
    correctAnswer: "B",
    explanation: "Respect for the law helps make Australian society safer and more peaceful for everyone.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 2 - Our freedoms",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 2,
    question: "Is English the national language of Australia?",
    optionA: "No, there is no national language",
    optionB: "Yes, English is the national language",
    optionC: "Yes, but only in some states",
    optionD: "No, multiple languages are equal",
    correctAnswer: "B",
    explanation: "English is the national language of Australia and is important for full participation in Australian society.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 2 - Our values",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 2,
    question: "Are Australians free to join any lawful organization?",
    optionA: "No, the government controls all organizations",
    optionB: "Yes, people can join any lawful organization",
    optionC: "Only political parties",
    optionD: "Only charities",
    correctAnswer: "B",
    explanation: "Freedom of association means Australians are free to join any lawful organization they choose.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 2 - Our freedoms",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 2,
    question: "What is parliamentary democracy?",
    optionA: "The military makes the laws",
    optionB: "Elected representatives make laws on behalf of the people",
    optionC: "The King makes all laws",
    optionD: "Judges create the laws",
    correctAnswer: "B",
    explanation: "Parliamentary democracy means elected representatives make laws on behalf of the people who elected them.",
    difficulty: "medium",
    source: "official_guide",
    sourceReference: "Part 2 - Democracy",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 2,
    question: "Can Australians choose their own spouse or partner?",
    optionA: "No, families must arrange marriages",
    optionB: "Yes, people are free to choose their own partner",
    optionC: "Only with government permission",
    optionD: "Only after age 30",
    correctAnswer: "B",
    explanation: "Freedom to choose your own spouse or partner is an important freedom in Australia.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 2 - Our freedoms",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 2,
    question: "Is there equality of opportunity in Australia?",
    optionA: "No, opportunities depend on wealth",
    optionB: "Yes, everyone should have a fair chance to succeed",
    optionC: "Only for citizens",
    optionD: "Only in certain industries",
    correctAnswer: "B",
    explanation: "Equality of opportunity is a fundamental Australian value - everyone should have a fair chance to succeed through their own efforts.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 2 - Our equalities",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 2,
    question: "What is the role of opposition parties in parliament?",
    optionA: "To support all government decisions",
    optionB: "To question and scrutinize the government",
    optionC: "To make laws without the government",
    optionD: "To appoint judges",
    correctAnswer: "B",
    explanation: "Opposition parties play an important role in questioning and scrutinizing government decisions in parliament.",
    difficulty: "medium",
    source: "official_guide",
    sourceReference: "Part 2 - Democracy",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 2,
    question: "Are all Australians equal under the law?",
    optionA: "No, some have special privileges",
    optionB: "Yes, all are equal before the law",
    optionC: "Only citizens are equal",
    optionD: "Only people born in Australia",
    correctAnswer: "B",
    explanation: "All Australians are equal before the law, regardless of background, wealth or position.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 2 - Our equalities",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 2,
    question: "Can Australians apply to work in any job they are qualified for?",
    optionA: "No, jobs are assigned by government",
    optionB: "Yes, people can apply for any job they're qualified for",
    optionC: "Only in certain sectors",
    optionD: "Only with special permits",
    correctAnswer: "B",
    explanation: "Australians have the freedom to apply for any job they are qualified for.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 2 - Our freedoms",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 2,
    question: "What does responsible government mean?",
    optionA: "The government can do whatever it wants",
    optionB: "The government is responsible to the people through parliament",
    optionC: "Only the Prime Minister is responsible",
    optionD: "The King controls the government",
    correctAnswer: "B",
    explanation: "Responsible government means the government is responsible to the people through their elected representatives in parliament.",
    difficulty: "medium",
    source: "official_guide",
    sourceReference: "Part 2 - Democracy",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 2,
    question: "Is it a criminal offence to encourage violence against others?",
    optionA: "No, free speech allows this",
    optionB: "Yes, inciting violence is a crime",
    optionC: "Only in certain circumstances",
    optionD: "Only if someone gets hurt",
    correctAnswer: "B",
    explanation: "Inciting violence against others is a criminal offence in Australia, even though free speech is valued.",
    difficulty: "medium",
    source: "official_guide",
    sourceReference: "Part 2 - Our freedoms",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 2,
    question: "Do Australian courts operate independently from the government?",
    optionA: "No, the government controls the courts",
    optionB: "Yes, courts are independent",
    optionC: "Only the High Court is independent",
    optionD: "Only during elections",
    correctAnswer: "B",
    explanation: "The independence of the courts is fundamental to the rule of law in Australia.",
    difficulty: "medium",
    source: "official_guide",
    sourceReference: "Part 2 - Rule of law",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 2,
    question: "What is the principle of 'innocent until proven guilty'?",
    optionA: "Everyone is guilty until they prove otherwise",
    optionB: "A person is considered innocent until proven guilty in court",
    optionC: "Only citizens get this protection",
    optionD: "It only applies to minor crimes",
    correctAnswer: "B",
    explanation: "The principle of 'innocent until proven guilty' is a fundamental right - a person is considered innocent until proven guilty in a court of law.",
    difficulty: "medium",
    source: "official_guide",
    sourceReference: "Part 2 - Rule of law",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 2,
    question: "Can Australians publicly criticize the government?",
    optionA: "No, this is illegal",
    optionB: "Yes, within the limits of the law",
    optionC: "Only during elections",
    optionD: "Only in private",
    correctAnswer: "B",
    explanation: "Australians can publicly criticize the government within the limits of the law - this is part of freedom of speech.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 2 - Our freedoms",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 2,
    question: "What does freedom of religion prohibit?",
    optionA: "Having any religion",
    optionB: "The government establishing an official religion",
    optionC: "Private religious practices",
    optionD: "Religious buildings",
    correctAnswer: "B",
    explanation: "Freedom of religion means the government cannot establish an official religion and people are free to practice any religion or none.",
    difficulty: "medium",
    source: "official_guide",
    sourceReference: "Part 2 - Our freedoms",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 2,
    question: "Are judges and magistrates independent from parliament?",
    optionA: "No, parliament controls judges",
    optionB: "Yes, they are independent",
    optionC: "Only in criminal cases",
    optionD: "Only federal judges",
    correctAnswer: "B",
    explanation: "Judges and magistrates are independent from parliament and make decisions based on law, not politics.",
    difficulty: "medium",
    source: "official_guide",
    sourceReference: "Part 2 - Rule of law",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 2,
    question: "Does Australia have a free press?",
    optionA: "No, the government controls all media",
    optionB: "Yes, the press is free from government control",
    optionC: "Only government newspapers exist",
    optionD: "Only during elections",
    correctAnswer: "B",
    explanation: "Australia has a free press that is independent from government control, which is essential for democracy.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 2 - Our freedoms",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 2,
    question: "What is habeas corpus?",
    optionA: "The right to a lawyer",
    optionB: "The right not to be imprisoned unlawfully",
    optionC: "The right to vote",
    optionD: "The right to free speech",
    correctAnswer: "B",
    explanation: "Habeas corpus is the right not to be imprisoned unlawfully - authorities must show legal cause for detention.",
    difficulty: "hard",
    source: "official_guide",
    sourceReference: "Part 2 - Rule of law",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 2,
    question: "Can people in Australia join a trade union?",
    optionA: "No, unions are illegal",
    optionB: "Yes, joining a union is voluntary",
    optionC: "Only in certain industries",
    optionD: "Only with employer permission",
    correctAnswer: "B",
    explanation: "People in Australia are free to join a trade union, and membership is voluntary.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 2 - Our freedoms",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 2,
    question: "What does representative democracy mean?",
    optionA: "The people vote on every law",
    optionB: "Elected representatives make decisions on behalf of the people",
    optionC: "The King makes all decisions",
    optionD: "Judges make the laws",
    correctAnswer: "B",
    explanation: "Representative democracy means the people elect representatives who make decisions and laws on their behalf.",
    difficulty: "medium",
    source: "official_guide",
    sourceReference: "Part 2 - Democracy",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 2,
    question: "Is there a separation of powers in Australia?",
    optionA: "No, one body has all power",
    optionB: "Yes, power is separated between parliament, executive and judiciary",
    optionC: "Only in federal government",
    optionD: "Only during wartime",
    correctAnswer: "B",
    explanation: "Australia has separation of powers between the legislature (parliament), executive (government) and judiciary (courts).",
    difficulty: "hard",
    source: "official_guide",
    sourceReference: "Part 2 - Democracy",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 2,
    question: "Can Australians start their own business?",
    optionA: "No, the government controls all business",
    optionB: "Yes, people are free to start lawful businesses",
    optionC: "Only with government approval",
    optionD: "Only certain types of businesses",
    correctAnswer: "B",
    explanation: "Australians are free to start their own lawful businesses as part of economic freedom.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 2 - Our freedoms",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 2,
    question: "Does respect for individual dignity and freedom mean forcing others to think like you?",
    optionA: "Yes, everyone must think the same",
    optionB: "No, people are free to have different beliefs and opinions",
    optionC: "Only in private",
    optionD: "Only about non-political matters",
    correctAnswer: "B",
    explanation: "Respect for individual dignity and freedom means allowing people to have different beliefs and opinions.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 2 - Our freedoms",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 2,
    question: "Can political parties compete for election in Australia?",
    optionA: "No, only one party is allowed",
    optionB: "Yes, multiple parties compete freely",
    optionC: "Only two parties are allowed",
    optionD: "Only with royal permission",
    correctAnswer: "B",
    explanation: "Australia has a multi-party democracy where different political parties compete freely for election.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 2 - Democracy",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 2,
    question: "Are women and men treated equally under Australian law?",
    optionA: "No, men have more rights",
    optionB: "Yes, men and women are equal under the law",
    optionC: "Only in certain states",
    optionD: "Only for citizens",
    correctAnswer: "B",
    explanation: "Men and women are equal under Australian law and have the same rights and opportunities.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 2 - Our equalities",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 2,
    question: "Is trial by jury available in Australia?",
    optionA: "No, only judges decide cases",
    optionB: "Yes, for serious criminal offences",
    optionC: "Only in civil cases",
    optionD: "Only for citizens",
    correctAnswer: "B",
    explanation: "Trial by jury is available for serious criminal offences in Australia, where citizens decide guilt or innocence.",
    difficulty: "medium",
    source: "official_guide",
    sourceReference: "Part 2 - Rule of law",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 2,
    question: "Can Australians travel freely within Australia?",
    optionA: "No, travel requires permits",
    optionB: "Yes, people can move freely between states",
    optionC: "Only citizens can travel freely",
    optionD: "Only with government approval",
    correctAnswer: "B",
    explanation: "Australians have the freedom to travel and move freely anywhere within Australia.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 2 - Our freedoms",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 2,
    question: "Is Australia's legal system based on English law traditions?",
    optionA: "No, it's based on European law",
    optionB: "Yes, based on British legal traditions",
    optionC: "No, it's entirely unique",
    optionD: "Yes, but only in some states",
    correctAnswer: "B",
    explanation: "Australia's legal system is based on British legal traditions, including common law and parliamentary democracy.",
    difficulty: "medium",
    source: "official_guide",
    sourceReference: "Part 2 - Rule of law",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 2,
    question: "Does everyone have the right to a fair trial in Australia?",
    optionA: "No, only citizens",
    optionB: "Yes, everyone is entitled to a fair trial",
    optionC: "Only in criminal cases",
    optionD: "Only if they can afford it",
    correctAnswer: "B",
    explanation: "Everyone in Australia is entitled to a fair trial, regardless of who they are.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 2 - Rule of law",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 2,
    question: "Can Australians belong to any political party they choose?",
    optionA: "No, the government assigns parties",
    optionB: "Yes, people can join any lawful political party",
    optionC: "Only approved parties",
    optionD: "Only during elections",
    correctAnswer: "B",
    explanation: "Australians are free to belong to any lawful political party they choose, or to no party at all.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 2 - Our freedoms",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 2,
    question: "What is the importance of an independent judiciary?",
    optionA: "It makes laws faster",
    optionB: "It ensures fair application of laws without political interference",
    optionC: "It reduces the number of trials",
    optionD: "It helps the government control people",
    correctAnswer: "B",
    explanation: "An independent judiciary ensures laws are applied fairly without political interference, protecting individual rights.",
    difficulty: "medium",
    source: "official_guide",
    sourceReference: "Part 2 - Rule of law",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 2,
    question: "Can Australians leave and return to Australia freely?",
    optionA: "No, exit visas are required",
    optionB: "Yes, Australian citizens can leave and return freely",
    optionC: "Only with government permission",
    optionD: "Only permanent residents can",
    correctAnswer: "B",
    explanation: "Australian citizens have the right to leave and return to Australia freely.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 2 - Our freedoms",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 2,
    question: "Does Australia protect freedom of assembly?",
    optionA: "No, gatherings are restricted",
    optionB: "Yes, people can gather peacefully for lawful purposes",
    optionC: "Only political gatherings",
    optionD: "Only with permits always",
    correctAnswer: "B",
    explanation: "Freedom of assembly allows people to gather peacefully for lawful purposes.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 2 - Our freedoms",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 2,
    question: "Are elections in Australia conducted fairly and regularly?",
    optionA: "No, only when government decides",
    optionB: "Yes, free and fair elections are held regularly",
    optionC: "Only at federal level",
    optionD: "Only every 10 years",
    correctAnswer: "B",
    explanation: "Free and fair elections are held regularly in Australia at all levels of government.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 2 - Democracy",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 2,
    question: "Can migrants maintain their cultural traditions in Australia?",
    optionA: "No, everyone must abandon their culture",
    optionB: "Yes, as long as they follow Australian laws",
    optionC: "Only in private",
    optionD: "Only certain cultures",
    correctAnswer: "B",
    explanation: "People can maintain their cultural traditions in Australia as long as they respect Australian laws and values.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 2 - Our freedoms",
    isValuesQuestion: false,
    isActive: true
  },

  // Additional Part 3 Questions - Government and the Law
  {
    categoryId: 3,
    question: "What does the Commonwealth of Australia Constitution Act establish?",
    optionA: "The states of Australia",
    optionB: "The federal government and its powers",
    optionC: "Local councils",
    optionD: "The police force",
    correctAnswer: "B",
    explanation: "The Commonwealth of Australia Constitution Act establishes the federal government and defines its powers.",
    difficulty: "medium",
    source: "official_guide",
    sourceReference: "Part 3 - The Constitution",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 3,
    question: "Can the Australian Constitution be changed?",
    optionA: "No, it is permanent",
    optionB: "Yes, by referendum where majority of voters and states agree",
    optionC: "Only by the Prime Minister",
    optionD: "Only by the King",
    correctAnswer: "B",
    explanation: "The Constitution can be changed by a referendum requiring a majority of voters nationally and a majority of states.",
    difficulty: "medium",
    source: "official_guide",
    sourceReference: "Part 3 - The Constitution",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 3,
    question: "How many territories does Australia have?",
    optionA: "One",
    optionB: "Two mainland territories",
    optionC: "Three",
    optionD: "Four",
    correctAnswer: "B",
    explanation: "Australia has two mainland territories: the Australian Capital Territory and the Northern Territory.",
    difficulty: "medium",
    source: "official_guide",
    sourceReference: "Part 3 - Government structure",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 3,
    question: "What is the lower house of federal parliament called?",
    optionA: "The Senate",
    optionB: "The House of Representatives",
    optionC: "The Legislative Assembly",
    optionD: "The House of Commons",
    correctAnswer: "B",
    explanation: "The lower house of federal parliament is called the House of Representatives.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 3 - Parliament",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 3,
    question: "Who chooses the ministers in the Australian Government?",
    optionA: "The King",
    optionB: "The Prime Minister",
    optionC: "The Governor-General",
    optionD: "The voters directly",
    correctAnswer: "B",
    explanation: "The Prime Minister chooses ministers to form the government.",
    difficulty: "medium",
    source: "official_guide",
    sourceReference: "Part 3 - The Executive",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 3,
    question: "What is the maximum term of the House of Representatives?",
    optionA: "2 years",
    optionB: "3 years",
    optionC: "4 years",
    optionD: "5 years",
    correctAnswer: "B",
    explanation: "The House of Representatives has a maximum term of 3 years.",
    difficulty: "medium",
    source: "official_guide",
    sourceReference: "Part 3 - Parliament",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 3,
    question: "What is the term length for senators?",
    optionA: "3 years",
    optionB: "4 years",
    optionC: "6 years",
    optionD: "8 years",
    correctAnswer: "C",
    explanation: "Senators are elected for a term of 6 years.",
    difficulty: "medium",
    source: "official_guide",
    sourceReference: "Part 3 - Parliament",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 3,
    question: "Who signs bills to make them law?",
    optionA: "The Prime Minister",
    optionB: "The Governor-General",
    optionC: "The Chief Justice",
    optionD: "The Speaker",
    correctAnswer: "B",
    explanation: "The Governor-General signs bills to make them law after they pass through parliament.",
    difficulty: "medium",
    source: "official_guide",
    sourceReference: "Part 3 - How laws are made",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 3,
    question: "What are the colors of the Australian flag?",
    optionA: "Red, white and blue",
    optionB: "Blue, white and red",
    optionC: "Green and gold",
    optionD: "Black, red and yellow",
    correctAnswer: "B",
    explanation: "The Australian National Flag is blue, white and red, featuring the Union Jack and Southern Cross.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 3 - National symbols",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 3,
    question: "What is Australia's system of government called?",
    optionA: "Republic",
    optionB: "Parliamentary democracy",
    optionC: "Dictatorship",
    optionD: "Absolute monarchy",
    correctAnswer: "B",
    explanation: "Australia has a parliamentary democracy system of government.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 3 - Government type",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 3,
    question: "What is a referendum?",
    optionA: "A regular election",
    optionB: "A vote to change the Constitution",
    optionC: "Appointment of a minister",
    optionD: "A court case",
    correctAnswer: "B",
    explanation: "A referendum is a vote to change the Australian Constitution.",
    difficulty: "medium",
    source: "official_guide",
    sourceReference: "Part 3 - The Constitution",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 3,
    question: "Who do state governments represent?",
    optionA: "The federal government",
    optionB: "People of their state",
    optionC: "Local councils",
    optionD: "The King",
    correctAnswer: "B",
    explanation: "State governments are elected by and represent the people of their state.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 3 - State government",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 3,
    question: "What is the role of local government?",
    optionA: "National defence",
    optionB: "Services like waste collection and local roads",
    optionC: "Foreign policy",
    optionD: "Immigration",
    correctAnswer: "B",
    explanation: "Local government provides services like waste collection, local roads, and community facilities.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 3 - Local government",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 3,
    question: "Who appoints the Governor-General?",
    optionA: "The Prime Minister",
    optionB: "The King on advice of the Prime Minister",
    optionC: "The voters",
    optionD: "The High Court",
    correctAnswer: "B",
    explanation: "The Governor-General is appointed by the King on the advice of the Prime Minister.",
    difficulty: "medium",
    source: "official_guide",
    sourceReference: "Part 3 - The Executive",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 3,
    question: "What is the leader of a state government called?",
    optionA: "Governor",
    optionB: "Premier",
    optionC: "Minister",
    optionD: "Mayor",
    correctAnswer: "B",
    explanation: "The leader of a state government is called the Premier (or Chief Minister in territories).",
    difficulty: "medium",
    source: "official_guide",
    sourceReference: "Part 3 - State government",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 3,
    question: "Who can vote in federal elections?",
    optionA: "Anyone over 18",
    optionB: "Australian citizens aged 18 and over",
    optionC: "Only property owners",
    optionD: "Only men",
    correctAnswer: "B",
    explanation: "Australian citizens aged 18 years and over are entitled and required to vote in federal elections.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 3 - Voting",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 3,
    question: "What is preferential voting?",
    optionA: "Voting for your preferred party only",
    optionB: "Ranking candidates in order of preference",
    optionC: "Voting twice",
    optionD: "Voting for multiple parties",
    correctAnswer: "B",
    explanation: "Preferential voting means ranking candidates in order of preference on the ballot paper.",
    difficulty: "medium",
    source: "official_guide",
    sourceReference: "Part 3 - Voting",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 3,
    question: "What happens if you don't vote in a federal election?",
    optionA: "Nothing",
    optionB: "You may receive a fine",
    optionC: "You lose citizenship",
    optionD: "You go to prison",
    correctAnswer: "B",
    explanation: "Voting is compulsory and you may receive a fine if you don't vote without a valid reason.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 3 - Voting",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 3,
    question: "Who is the head of the Australian Government?",
    optionA: "The Governor-General",
    optionB: "The Prime Minister",
    optionC: "The King",
    optionD: "The Chief Justice",
    correctAnswer: "B",
    explanation: "The Prime Minister is the head of the Australian Government.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 3 - The Executive",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 3,
    question: "What is the leader of a local council called?",
    optionA: "Premier",
    optionB: "Mayor or Shire President",
    optionC: "Governor",
    optionD: "Minister",
    correctAnswer: "B",
    explanation: "The leader of a local council is called the Mayor or Shire President.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 3 - Local government",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 3,
    question: "What are the two main political parties in Australia?",
    optionA: "Democrats and Republicans",
    optionB: "Liberal Party and Australian Labor Party",
    optionC: "Conservative and Labour",
    optionD: "National and Green",
    correctAnswer: "B",
    explanation: "The two main political parties are the Liberal Party and the Australian Labor Party.",
    difficulty: "medium",
    source: "official_guide",
    sourceReference: "Part 3 - Political parties",
    isValuesQuestion: false,
    isActive: true
  },
  {
    categoryId: 3,
    question: "When must a federal election be held?",
    optionA: "Every 2 years",
    optionB: "At least every 3 years",
    optionC: "Every 4 years",
    optionD: "Every 5 years",
    correctAnswer: "B",
    explanation: "A federal election must be held at least every 3 years for the House of Representatives.",
    difficulty: "medium",
    source: "official_guide",
    sourceReference: "Part 3 - Elections",
    isValuesQuestion: false,
    isActive: true
  },

  // Additional Part 4 Questions - Australian Values
  {
    categoryId: 4,
    question: "Should people in Australia make an effort to learn English?",
    optionA: "No, it's not important",
    optionB: "Yes, English helps people participate fully in Australian society",
    optionC: "Only if they work in government",
    optionD: "Only if they are citizens",
    correctAnswer: "B",
    explanation: "Learning English helps people participate fully in Australian society and is an important part of integration.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 4 - Australian values",
    isValuesQuestion: true,
    isActive: true
  },
  {
    categoryId: 4,
    question: "Is violence an acceptable way to resolve disputes in Australia?",
    optionA: "Yes, if provoked",
    optionB: "No, violence is not acceptable to resolve disputes",
    optionC: "Sometimes",
    optionD: "Only in self-defense",
    correctAnswer: "B",
    explanation: "Violence is never an acceptable way to resolve disputes or disagreements in Australian society.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 4 - Australian values",
    isValuesQuestion: true,
    isActive: true
  },
  {
    categoryId: 4,
    question: "Should Australians tolerate those who disagree with their views?",
    optionA: "No, only agree with like-minded people",
    optionB: "Yes, mutual respect and tolerance of different views is important",
    optionC: "Only on political matters",
    optionD: "Only if required by law",
    correctAnswer: "B",
    explanation: "Mutual respect and tolerance of different views and beliefs is a fundamental Australian value.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 4 - Australian values",
    isValuesQuestion: true,
    isActive: true
  },
  {
    categoryId: 4,
    question: "Are men and women equal partners in Australia?",
    optionA: "No, men are superior",
    optionB: "Yes, men and women have equal rights and opportunities",
    optionC: "Only in the workplace",
    optionD: "Only in public life",
    correctAnswer: "B",
    explanation: "Men and women have equal rights and are equal partners in Australian society.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 4 - Australian values",
    isValuesQuestion: true,
    isActive: true
  },
  {
    categoryId: 4,
    question: "Is it acceptable to use violence against your spouse in Australia?",
    optionA: "Yes, within the family",
    optionB: "No, it is a serious crime",
    optionC: "Only if provoked",
    optionD: "It depends on the situation",
    correctAnswer: "B",
    explanation: "Family violence is a serious crime in Australia and is never acceptable.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 4 - Australian values",
    isValuesQuestion: true,
    isActive: true
  },
  {
    categoryId: 4,
    question: "Should Australians show compassion for those in need?",
    optionA: "No, people should only help themselves",
    optionB: "Yes, compassion for those in need is an important Australian value",
    optionC: "Only for family members",
    optionD: "Only if paid to do so",
    correctAnswer: "B",
    explanation: "Compassion for those in need is an important Australian value.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 4 - Australian values",
    isValuesQuestion: true,
    isActive: true
  },
  {
    categoryId: 4,
    question: "Is it acceptable to humiliate or intimidate people because of their religion?",
    optionA: "Yes, if their religion is different",
    optionB: "No, everyone should be treated with dignity and respect",
    optionC: "Only certain religions",
    optionD: "It depends on the situation",
    correctAnswer: "B",
    explanation: "Everyone should be treated with dignity and respect regardless of their religion. Discrimination is not acceptable.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 4 - Australian values",
    isValuesQuestion: true,
    isActive: true
  },
  {
    categoryId: 4,
    question: "Should people resolve disagreements through discussion and peaceful means?",
    optionA: "No, force is more effective",
    optionB: "Yes, peaceful resolution is a key Australian value",
    optionC: "Only in public places",
    optionD: "Only when required by police",
    correctAnswer: "B",
    explanation: "Resolving disagreements peacefully through discussion is a key Australian value.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 4 - Australian values",
    isValuesQuestion: true,
    isActive: true
  },
  {
    categoryId: 4,
    question: "Do Australian values include respect for freedom and dignity?",
    optionA: "No, collective needs are more important",
    optionB: "Yes, respect for individual freedom and dignity is fundamental",
    optionC: "Only for citizens",
    optionD: "Only in certain situations",
    correctAnswer: "B",
    explanation: "Respect for the freedom and dignity of the individual is a fundamental Australian value.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 4 - Australian values",
    isValuesQuestion: true,
    isActive: true
  },
  {
    categoryId: 4,
    question: "Is it acceptable to force someone to marry against their will?",
    optionA: "Yes, if it's a cultural practice",
    optionB: "No, forced marriage is a crime",
    optionC: "Only arranged marriages",
    optionD: "It depends on the age",
    correctAnswer: "B",
    explanation: "Forced marriage is a crime in Australia. Everyone has the right to choose their own spouse.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 4 - Australian values",
    isValuesQuestion: true,
    isActive: true
  },
  {
    categoryId: 4,
    question: "Should parents allow their children to participate in Australian society?",
    optionA: "No, children should stay isolated",
    optionB: "Yes, children should have opportunities to participate",
    optionC: "Only boys",
    optionD: "Only after age 18",
    correctAnswer: "B",
    explanation: "Children should have equal opportunities to participate in Australian society regardless of gender.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 4 - Australian values",
    isValuesQuestion: true,
    isActive: true
  },
  {
    categoryId: 4,
    question: "Is it important to respect different cultures and beliefs in Australia?",
    optionA: "No, everyone must be the same",
    optionB: "Yes, as long as they don't break Australian law",
    optionC: "Only certain cultures",
    optionD: "Only for citizens",
    correctAnswer: "B",
    explanation: "Respecting different cultures and beliefs is important, as long as they don't break Australian law.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 4 - Australian values",
    isValuesQuestion: true,
    isActive: true
  },
  {
    categoryId: 4,
    question: "Do both men and women have the right to work in Australia?",
    optionA: "No, only men should work",
    optionB: "Yes, men and women have equal rights to work",
    optionC: "Only unmarried women",
    optionD: "Only in certain jobs",
    correctAnswer: "B",
    explanation: "Men and women have equal rights to work and pursue careers in Australia.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 4 - Australian values",
    isValuesQuestion: true,
    isActive: true
  },
  {
    categoryId: 4,
    question: "Should Australians help people if they need assistance?",
    optionA: "No, everyone is on their own",
    optionB: "Yes, helping those in need shows compassion",
    optionC: "Only family members",
    optionD: "Only if paid",
    correctAnswer: "B",
    explanation: "The spirit of mateship and compassion means helping those who need assistance.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 4 - Australian values",
    isValuesQuestion: true,
    isActive: true
  },
  {
    categoryId: 4,
    question: "Is religious extremism compatible with Australian values?",
    optionA: "Yes, all religious practices are acceptable",
    optionB: "No, violent extremism is not compatible with Australian values",
    optionC: "Only certain religions",
    optionD: "It depends on the situation",
    correctAnswer: "B",
    explanation: "Violent extremism, including religious extremism, is not compatible with Australian values and laws.",
    difficulty: "medium",
    source: "official_guide",
    sourceReference: "Part 4 - Australian values",
    isValuesQuestion: true,
    isActive: true
  },
  {
    categoryId: 4,
    question: "Can a person choose to be single or marry in Australia?",
    optionA: "No, marriage is compulsory",
    optionB: "Yes, people have the freedom to choose",
    optionC: "Only for men",
    optionD: "Only with family permission",
    correctAnswer: "B",
    explanation: "People in Australia have the freedom to choose whether to marry or remain single.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 4 - Australian values",
    isValuesQuestion: true,
    isActive: true
  },
  {
    categoryId: 4,
    question: "Is it acceptable to prevent someone from working because of their gender?",
    optionA: "Yes, in certain jobs",
    optionB: "No, this is illegal discrimination",
    optionC: "Only for married women",
    optionD: "Only in private companies",
    correctAnswer: "B",
    explanation: "Preventing someone from working because of their gender is illegal discrimination in Australia.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 4 - Australian values",
    isValuesQuestion: true,
    isActive: true
  },
  {
    categoryId: 4,
    question: "Should Australians value giving others a 'fair go'?",
    optionA: "No, competition is all that matters",
    optionB: "Yes, giving everyone a fair chance is an Australian value",
    optionC: "Only in sports",
    optionD: "Only for citizens",
    correctAnswer: "B",
    explanation: "Giving everyone a 'fair go' - a fair chance to succeed - is an important Australian value.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 4 - Australian values",
    isValuesQuestion: true,
    isActive: true
  },
  {
    categoryId: 4,
    question: "Is it acceptable to use threats or violence to settle arguments?",
    optionA: "Yes, if you're angry",
    optionB: "No, peaceful resolution is the Australian way",
    optionC: "Only minor violence",
    optionD: "Only in private",
    correctAnswer: "B",
    explanation: "Using threats or violence to settle arguments is not acceptable. Peaceful resolution is the Australian way.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 4 - Australian values",
    isValuesQuestion: true,
    isActive: true
  },
  {
    categoryId: 4,
    question: "Do girls and boys have equal access to education in Australia?",
    optionA: "No, only boys should be educated",
    optionB: "Yes, girls and boys have equal access to education",
    optionC: "Only in primary school",
    optionD: "Only in private schools",
    correctAnswer: "B",
    explanation: "Girls and boys have equal access to education in Australia.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 4 - Australian values",
    isValuesQuestion: true,
    isActive: true
  },
  {
    categoryId: 4,
    question: "Is racial discrimination acceptable in Australia?",
    optionA: "Yes, against certain groups",
    optionB: "No, racial discrimination is illegal",
    optionC: "Only in private",
    optionD: "Only verbally",
    correctAnswer: "B",
    explanation: "Racial discrimination is illegal and goes against Australian values of equality and respect.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 4 - Australian values",
    isValuesQuestion: true,
    isActive: true
  },
  {
    categoryId: 4,
    question: "Should Australians respect the rule of law?",
    optionA: "No, laws can be ignored",
    optionB: "Yes, respect for the rule of law is essential",
    optionC: "Only when convenient",
    optionD: "Only major laws",
    correctAnswer: "B",
    explanation: "Respect for the rule of law is an essential Australian value. Everyone must follow the law.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 4 - Australian values",
    isValuesQuestion: true,
    isActive: true
  },
  {
    categoryId: 4,
    question: "Can people practice their culture as long as they respect Australian laws?",
    optionA: "No, all cultural practices must be abandoned",
    optionB: "Yes, cultural practices are welcome if they respect Australian laws and values",
    optionC: "Only at home",
    optionD: "Only certain cultures",
    correctAnswer: "B",
    explanation: "People can practice their culture in Australia as long as they respect Australian laws and values.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 4 - Australian values",
    isValuesQuestion: true,
    isActive: true
  },
  {
    categoryId: 4,
    question: "Is it important to treat all people with equal respect?",
    optionA: "No, some people deserve less respect",
    optionB: "Yes, everyone deserves equal respect",
    optionC: "Only people you agree with",
    optionD: "Only people from your culture",
    correctAnswer: "B",
    explanation: "Treating all people with equal respect regardless of background is a fundamental Australian value.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 4 - Australian values",
    isValuesQuestion: true,
    isActive: true
  },
  {
    categoryId: 4,
    question: "Should Australians value equality of opportunity?",
    optionA: "No, only the wealthy should succeed",
    optionB: "Yes, everyone should have equal opportunity to succeed",
    optionC: "Only for certain groups",
    optionD: "Only in government jobs",
    correctAnswer: "B",
    explanation: "Equality of opportunity - everyone having a chance to succeed - is a core Australian value.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 4 - Australian values",
    isValuesQuestion: true,
    isActive: true
  },
  {
    categoryId: 4,
    question: "Is female genital mutilation legal in Australia?",
    optionA: "Yes, if it's cultural",
    optionB: "No, it is a serious crime",
    optionC: "Only with consent",
    optionD: "Only in certain states",
    correctAnswer: "B",
    explanation: "Female genital mutilation is a serious crime in Australia and goes against Australian values.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 4 - Australian values",
    isValuesQuestion: true,
    isActive: true
  },
  {
    categoryId: 4,
    question: "Should people respect others' right to express their own culture?",
    optionA: "No, only one culture should exist",
    optionB: "Yes, as long as it respects Australian laws",
    optionC: "Only European cultures",
    optionD: "Only in designated areas",
    correctAnswer: "B",
    explanation: "People should respect others' right to express their culture, as long as it respects Australian laws and values.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 4 - Australian values",
    isValuesQuestion: true,
    isActive: true
  },
  {
    categoryId: 4,
    question: "Is it acceptable to discriminate against someone because of their disability?",
    optionA: "Yes, disabled people have fewer rights",
    optionB: "No, discrimination is illegal and wrong",
    optionC: "Only in employment",
    optionD: "Only for severe disabilities",
    correctAnswer: "B",
    explanation: "Discrimination against someone because of their disability is illegal and against Australian values.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 4 - Australian values",
    isValuesQuestion: true,
    isActive: true
  },
  {
    categoryId: 4,
    question: "Should Australians support a spirit of egalitarianism?",
    optionA: "No, hierarchy is more important",
    optionB: "Yes, treating people equally regardless of background is important",
    optionC: "Only for certain groups",
    optionD: "Only in public",
    correctAnswer: "B",
    explanation: "A spirit of egalitarianism - treating people equally regardless of their background - is an Australian value.",
    difficulty: "medium",
    source: "official_guide",
    sourceReference: "Part 4 - Australian values",
    isValuesQuestion: true,
    isActive: true
  },
  {
    categoryId: 4,
    question: "Do both men and women have the right to participate in community life?",
    optionA: "No, only men",
    optionB: "Yes, men and women have equal rights to participate",
    optionC: "Only unmarried people",
    optionD: "Only in certain communities",
    correctAnswer: "B",
    explanation: "Men and women have equal rights to participate fully in community life in Australia.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 4 - Australian values",
    isValuesQuestion: true,
    isActive: true
  },
  {
    categoryId: 4,
    question: "Is it acceptable to prevent women from leaving the house?",
    optionA: "Yes, for their safety",
    optionB: "No, everyone has freedom of movement",
    optionC: "Only if the husband decides",
    optionD: "Only in certain cultures",
    correctAnswer: "B",
    explanation: "Preventing women from leaving the house violates their freedom of movement and is against Australian values.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 4 - Australian values",
    isValuesQuestion: true,
    isActive: true
  },
  {
    categoryId: 4,
    question: "Should Australians value peacefulness?",
    optionA: "No, strength through force is better",
    optionB: "Yes, peacefulness is an important Australian value",
    optionC: "Only in public",
    optionD: "Only when required",
    correctAnswer: "B",
    explanation: "Peacefulness is an important Australian value. Australians resolve disagreements peacefully.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 4 - Australian values",
    isValuesQuestion: true,
    isActive: true
  },
  {
    categoryId: 4,
    question: "Can people choose to have children or not in Australia?",
    optionA: "No, having children is compulsory",
    optionB: "Yes, people are free to choose",
    optionC: "Only married couples can choose",
    optionD: "Only with government approval",
    correctAnswer: "B",
    explanation: "People in Australia have the freedom to choose whether or not to have children.",
    difficulty: "easy",
    source: "official_guide",
    sourceReference: "Part 4 - Australian values",
    isValuesQuestion: true,
    isActive: true
  },
];

// Study Materials Content - Extracted from Official Guide
export const studyMaterialsContent: Omit<InsertStudyMaterial, 'createdAt'>[] = [
  {
    categoryId: 1,
    partNumber: 1,
    title: "Aboriginal and Torres Strait Islander peoples",
    section: "Australia's First Inhabitants",
    content: `Australia's first inhabitants are the Aboriginal and Torres Strait Islander peoples, who have the oldest continuous cultures and traditions in the world.

Aboriginal people are from mainland Australia and Tasmania. Archaeological records indicate that Aboriginal peoples arrived in Australia between 65,000 and 40,000 years ago. However, Aboriginal peoples believe they are central to the creation stories of this land.

Torres Strait Islander people are from islands between the northern tip of Queensland and Papua New Guinea.

Aboriginal and Torres Strait Islander peoples have age-old beliefs and traditions that still guide them today. They have a deep connection with the land, which is expressed in their stories, art and dance. Indigenous cultures are diverse and an important part of Australia's national identity.`,
    orderIndex: 1,
    isActive: true
  },
  {
    categoryId: 1,
    partNumber: 1,
    title: "Early days of European settlement",
    section: "The First Fleet",
    content: `European settlement started when the first 11 convict ships, known as the 'First Fleet', arrived from Great Britain on 26 January 1788.

At this time, British laws were harsh and the jails could not hold the large number of people imprisoned for their crimes. To manage this problem, the British Government decided to transport convicts to the new colony of New South Wales.

The first Governor of the colony was Captain Arthur Phillip. The colony survived, and as more convicts and free settlers arrived, it grew and developed.

Early free settlers came from Great Britain and Ireland. This British and Irish heritage has had a major influence on Australia's recent history, culture and politics.`,
    orderIndex: 2,
    isActive: true
  },
  {
    categoryId: 1,
    partNumber: 1,
    title: "The Australian gold rush",
    section: "Gold Discovery",
    content: `In 1851, a 'gold rush' began when gold was discovered in the colonies of New South Wales and Victoria. People from all around the world came to try to make their fortunes.

Chinese people arriving at this time were the first large group of migrants not from Europe. In 10 years, Australia's population more than doubled.`,
    orderIndex: 3,
    isActive: true
  },
  {
    categoryId: 1,
    partNumber: 1,
    title: "The nation of Australia",
    section: "Federation",
    content: `In 1901, the separate colonies were united into a federation of states called the Commonwealth of Australia. Our national democratic institutions, including our national parliament, government and the High Court were established under the new Australian Constitution.

In 1901, Australia's population was about four million. This number did not include Aboriginal and Torres Strait Islander peoples. They were not included in official estimates until after a Referendum in 1967.`,
    orderIndex: 4,
    isActive: true
  },
  {
    categoryId: 2,
    partNumber: 2,
    title: "Australia's democratic beliefs",
    section: "Democracy and Freedom",
    content: `Australia is a democracy. In a democracy, the government is elected by the people and must respect the rights and freedoms of individuals.

Australian values include:
• Respect for the freedom and dignity of the individual
• Freedom of religion
• Commitment to the rule of law
• Parliamentary democracy
• Equality of men and women
• Equality of opportunity
• A spirit of egalitarianism that values mutual respect and compassion for those in need

These values are central to Australian citizenship and way of life.`,
    orderIndex: 5,
    isActive: true
  },
  {
    categoryId: 3,
    partNumber: 3,
    title: "Government and the law in Australia",
    section: "How Government Works",
    content: `Australia is a parliamentary democracy with three levels of government:
1. Federal (Commonwealth) government
2. State and territory governments
3. Local government

The Parliament makes and changes laws. It has two houses:
• The House of Representatives
• The Senate

The government is formed by the party or coalition with the majority in the House of Representatives.

The High Court is Australia's highest court and final court of appeal.`,
    orderIndex: 6,
    isActive: true
  },
  {
    categoryId: 4,
    partNumber: 4,
    title: "Australian values",
    section: "Core Values",
    content: `Australian citizenship is about living out shared values in everyday life. These values include:

• Respect for equal worth, dignity and freedom of the individual
• Freedom of speech and association
• Freedom of religion and a secular government
• Support for parliamentary democracy and the rule of law
• Equality under the law
• Equality of men and women
• Equality of opportunity
• Peacefulness
• Tolerance, mutual respect and compassion for those in need

All Australians are expected to uphold and promote these values.`,
    orderIndex: 7,
    isActive: true
  }
];

// Flashcards based on official content - 20 unique questions
export const officialFlashcards: Omit<InsertFlashcard, 'createdAt'>[] = [
  {
    categoryId: 1,
    front: "Who are Australia's first inhabitants?",
    back: "Aboriginal and Torres Strait Islander peoples, who have the oldest continuous cultures and traditions in the world.",
    isActive: true
  },
  {
    categoryId: 1,
    front: "When did the First Fleet arrive in Australia?",
    back: "26 January 1788",
    isActive: true
  },
  {
    categoryId: 1,
    front: "When did Australia become a nation?",
    back: "1 January 1901, when the separate colonies united to form the Commonwealth of Australia",
    isActive: true
  },
  {
    categoryId: 1,
    front: "What is Australia's capital city?",
    back: "Canberra",
    isActive: true
  },
  {
    categoryId: 1,
    front: "What is Australia's national anthem?",
    back: "Advance Australia Fair",
    isActive: true
  },
  {
    categoryId: 1,
    front: "When is Australia Day celebrated?",
    back: "26 January each year, the anniversary of the arrival of the First Fleet in 1788.",
    isActive: true
  },
  {
    categoryId: 1,
    front: "When is Anzac Day commemorated?",
    back: "25 April each year, remembering those who served and died in wars and peacekeeping operations.",
    isActive: true
  },
  {
    categoryId: 1,
    front: "What is Australia's national flower?",
    back: "The golden wattle",
    isActive: true
  },
  {
    categoryId: 1,
    front: "What are Australia's national colours?",
    back: "Green and gold, the colours of the golden wattle.",
    isActive: true
  },
  {
    categoryId: 2,
    front: "What is the Rule of Law?",
    back: "Everyone must follow the law, including those who make it. No one is above the law.",
    isActive: true
  },
  {
    categoryId: 2,
    front: "What does freedom of religion mean?",
    back: "People can practice any religion they choose, or no religion at all.",
    isActive: true
  },
  {
    categoryId: 2,
    front: "Is Australia's government secular?",
    back: "Yes, it operates separately from churches or other religious entities.",
    isActive: true
  },
  {
    categoryId: 2,
    front: "What does 'a fair go' mean?",
    back: "Equal opportunity - what someone achieves should result from their talents, work and effort, not their background.",
    isActive: true
  },
  {
    categoryId: 3,
    front: "What are the three levels of government in Australia?",
    back: "Federal (Commonwealth), State/Territory, and Local government",
    isActive: true
  },
  {
    categoryId: 3,
    front: "Is voting compulsory in Australia?",
    back: "Yes, voting is compulsory for all Australian citizens aged 18 years and over in federal and state elections.",
    isActive: true
  },
  {
    categoryId: 3,
    front: "How many senators are there in total?",
    back: "76 senators: 12 from each of the 6 states plus 2 each from the ACT and NT.",
    isActive: true
  },
  {
    categoryId: 3,
    front: "Who is Australia's Head of State?",
    back: "The King of Australia, His Majesty King Charles III.",
    isActive: true
  },
  {
    categoryId: 4,
    front: "Are men and women equal in Australia?",
    back: "Yes, Australian law and values support equality between men and women, giving them equal rights and opportunities.",
    isActive: true
  },
  {
    categoryId: 4,
    front: "What are Australian values based on?",
    back: "Freedom, respect, fairness and equality of opportunity.",
    isActive: true
  },
  {
    categoryId: 4,
    front: "Do Australian laws apply to all people in Australia?",
    back: "Yes, regardless of background or culture, all people in Australia must follow Australian laws.",
    isActive: true
  }
];
